spring:
  profiles:
    active: ${SPRING_PROFILE:local}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        # 이 값들은 네이버 OAuth2 API 문서에서 제공하는 기본적인 설정이므로, 네이버 API에 맞춰 고정된 값으로 사용되며, 특별한 사유가 없다면 변경하지 않아도 된다.
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   # authorization-uri: 네이버 로그인 페이지로 리디렉션하여 사용자에게 인증을 요청하는 URI.
            token-uri: https://nid.naver.com/oauth2.0/token   #token-uri: 인증 코드로 액세스 토큰을 받기 위한 URI
            user-info-uri: https://openapi.naver.com/v1/nid/me    #user-info-uri: 액세스 토큰을 통해 사용자 정보를 가져오는 URI
            user-name-attribute: response     #user-name-attribute: 네이버에서 반환하는 사용자 정보 중 사용자 이름을 나타내는 속성 (response는 네이버에서 기본적으로 반환되는 사용자 정보 객체의 최상위 필드)


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}